require:
  - rubocop-rails
inherit_gem:
  rubocop-rails_config:
    - config/rails.yml
AllCops:
  Exclude:
    - '**/tmp/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    - 'actionmailbox/test/dummy/**/*'
    - 'actiontext/test/dummy/**/*'
    - '**/node_modules/**/*'
    - '**/db/**/*'
    - '**/lib/**/*'
    - '**/config/**/*'
    - '**/bin/**/*'
Layout/LineLength:
  Max: 105
Layout/ExtraSpacing:
  Enabled: true
# Check quotes usage according to lint rule below.
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
# Detect hard tabs, no hard tabs.
Layout/IndentationStyle:
  Enabled: true
# Empty lines should not have any spaces.
Layout/TrailingEmptyLines:
  Enabled: true
# No trailing whitespace.
Layout/TrailingWhitespace:
  Enabled: true
# Use Ruby >= 1.9 syntax for hashes. Prefer { a: :b } over { :a => :b }.
Style/HashSyntax:
  Enabled: true
