default: &default
  adapter: postgresql
  encoding: unicode
  pool:  15
  host: localhost
  username: 'postgres'
  password: 'postgres'
  port: 5432

development:
  <<: *default
  database: pennylane

  # test:
  # <<: *default
  # database: db/test.pennylane

  production:
    <<: *default
    database: delj9t91a53fjv
    host: "52.70.186.184"
